# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

inhibit_all_warnings!

target 'Swift-Common' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Rx
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'ReactorKit'
  
  # Network
  pod 'Moya/RxSwift'
  pod 'Alamofire'

  target 'Swift-CommonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Swift-CommonUITests' do
    # Pods for testing
  end

end

post_install do |installer|

  # if it is not available, please install https://github.com/vmg/redcarpet
  pods_acknowledgements_path = '"Pods/Target Support Files/Pods-Swift-Common/Pods-Swift-Common-acknowledgements.markdown"'
  licenses_path = 'Swift-Common/Resources/licenses.html'
  system 'redcarpet --version'
  if $?.success?
    system 'cat Swift-Common/Resources/licenses_header.html > ' + licenses_path
    system 'redcarpet ' + pods_acknowledgements_path + ' >> ' + licenses_path
    system 'cat Swift-Common/Resources/licenses_footer.html >> ' + licenses_path
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
